# Generated by Django 5.1.2 on 2024-10-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0001_initial"),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="author.author",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="articles", to="article.category"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="article.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="author.author",
            ),
        ),
        migrations.AddField(
            model_name="epaper",
            name="categories",
            field=models.ManyToManyField(related_name="epaper", to="article.category"),
        ),
        migrations.AddField(
            model_name="like",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_likes",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="author.author",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(related_name="articles", to="article.tag"),
        ),
        migrations.AddField(
            model_name="videonews",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos_news",
                to="author.author",
            ),
        ),
        migrations.AddField(
            model_name="videonews",
            name="categories",
            field=models.ManyToManyField(
                related_name="video_news", to="article.category"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("article", "author")},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="article_slug_45f26a_idx"),
        ),
    ]
