# Generated by Django 5.1.2 on 2024-10-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epaper",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="epaper",
            name="description",
        ),
        migrations.AddField(
            model_name="epaper",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="epaper",
            name="date_published",
            field=models.DateField(blank=True, null=True),
        ),
    ]
