# Generated by Django 5.1.2 on 2024-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_remove_epaper_categories_remove_epaper_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="epaper",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="videonews",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="videonews",
            name="date_published",
            field=models.DateTimeField(),
        ),
    ]
