# Generated by Django 5.1.2 on 2024-10-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_epaper_status_videonews_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
