# Generated by Django 5.1.2 on 2024-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_remove_comment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reader",
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
