# Generated by Django 5.1.2 on 2024-10-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photogallery",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="photogallery",
            name="description",
        ),
        migrations.RemoveField(
            model_name="videogallery",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="videogallery",
            name="description",
        ),
    ]
